version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      nuget:
        patterns: ["*"]

  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet-sdk:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
    groups:
      devcontainers:
        patterns: ["*"]
