<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Cap.Rand</RootNamespace>
    <Description>Randomness capabilities over RandomNumberGenerator.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Cap.Primitives/Cap.Primitives.csproj" />
  </ItemGroup>

</Project>
