<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Cap.Primitives.Tests</RootNamespace>
    <AssemblyName>Cap.Primitives.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Cap.Primitives/Cap.Primitives.csproj" />
  </ItemGroup>

</Project>
