<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PluginHost.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Cap.Std/Cap.Std.csproj" />
    <ProjectReference Include="../../../src/Cap.Primitives/Cap.Primitives.csproj" />
  </ItemGroup>

</Project>
